const content = require("./article")
'$2a$10$G1gFlsh/CXKhqCNtymu3g.DNxHjdBnmaAmC/pQ0fWdzlGufbKAn6S'
module.exports = [
    /** 前端 -----------------------------------------------------------------------------*/
    {
        // "article_id": 7,
        "user_id": 20,
        "category_id": 1,
        "tag_ids": [2, 3],
        "link_url": "",
        "cover_image": "",
        "title": "Vue前端实现HTML转PDF并导出 （测试标题 前端）",
        "brief_content": "这里是一个摘要（测试摘要 ）",
        "content": content,
        "visible_level": "0",
        "view_count": 0,
        "status": "1",
    },
    {
        // "article_id": 7,
        "user_id": 20,
        "category_id": 1,
        "tag_ids": [1, 3],
        "link_url": "",
        "cover_image": "",
        "title": "GitHub 上 9 个美观大气的后台管理系统 （测试标题 前端）",
        "brief_content": "这里是一个摘要（测试摘要 ）",
        "content": content,
        "visible_level": "0",
        "view_count": 0,
        "status": "1",
    },
    {
        // "article_id": 7,
        "user_id": 20,
        "category_id": 1,
        "tag_ids": [1,3],
        "link_url": "",
        "cover_image": "",
        "title": "前端面试必会网络之跨域问题解决 （测试标题 前端）",
        "brief_content": "这里是一个摘要（测试摘要 ）",
        "content": content,
        "visible_level": "0",
        "view_count": 0,
        "status": "1",
    },
    {
        // "article_id": 7,
        "user_id": 20,
        "category_id": 1,
        "tag_ids": [1, 2, 3],
        "link_url": "",
        "cover_image": "",
        "title": "前端基石：高阶函数之柯里化、组合函数、惰性思想 （测试标题 前端）",
        "brief_content": "这里是一个摘要（测试摘要 ）",
        "content": content,
        "visible_level": "0",
        "view_count": 0,
        "status": "1",
    },
    {
        // "article_id": 7,
        "user_id": 20,
        "category_id": 1,
        "tag_ids": [1, 2, 3],
        "link_url": "",
        "cover_image": "",
        "title": "你可能不知道的 Event Loop （测试标题 前端）",
        "brief_content": "这里是一个摘要（测试摘要 ）",
        "content": content,
        "visible_level": "0",
        "view_count": 0,
        "status": "1",
    },
    {
        // "article_id": 7,
        "user_id": 20,
        "category_id": 1,
        "tag_ids": [1, 2, 3],
        "link_url": "",
        "cover_image": "",
        "title": "让你的小程序用上原汁原味的 Tailwind/Windi CSS (JIT 兼容版) （测试标题 前端）",
        "brief_content": "这里是一个摘要（测试摘要 ）",
        "content": content,
        "visible_level": "0",
        "view_count": 0,
        "status": "1",
    },

    /** 后端 -----------------------------------------------------------------------------*/
    {
        // "article_id": 7,
        "user_id": 20,
        "category_id": 2,
        "tag_ids": [1, 2],
        "link_url": "",
        "cover_image": "",
        "title": "Vue前端实现HTML转PDF并导出 （测试标题 后端）",
        "brief_content": "这里是一个摘要（测试摘要 ）",
        "content": content,
        "visible_level": "0",
        "view_count": 0,
        "status": "1",
    },
    {
        // "article_id": 7,
        "user_id": 20,
        "category_id": 2,
        "tag_ids": [2, 3],
        "link_url": "",
        "cover_image": "",
        "title": "GitHub 上 9 个美观大气的后台管理系统 （测试标题 后端）",
        "brief_content": "这里是一个摘要（测试摘要 ）",
        "content": content,
        "visible_level": "0",
        "view_count": 0,
        "status": "1",
    },
    {
        // "article_id": 7,
        "user_id": 20,
        "category_id": 2,
        "tag_ids": [2, 3],
        "link_url": "",
        "cover_image": "",
        "title": "前端面试必会网络之跨域问题解决 （测试标题 后端）",
        "brief_content": "这里是一个摘要（测试摘要 ）",
        "content": content,
        "visible_level": "0",
        "view_count": 0,
        "status": "1",
    },
    {
        // "article_id": 7,
        "user_id": 20,
        "category_id": 2,
        "tag_ids": [1, 2],
        "link_url": "",
        "cover_image": "",
        "title": "前端基石：高阶函数之柯里化、组合函数、惰性思想 （测试标题 后端）",
        "brief_content": "这里是一个摘要（测试摘要 ）",
        "content": content,
        "visible_level": "0",
        "view_count": 0,
        "status": "1",
    },
    {
        // "article_id": 7,
        "user_id": 20,
        "category_id": 2,
        "tag_ids": [2],
        "link_url": "",
        "cover_image": "",
        "title": "你可能不知道的 Event Loop （测试标题 后端）",
        "brief_content": "这里是一个摘要（测试摘要 ）",
        "content": content,
        "visible_level": "0",
        "view_count": 0,
        "status": "1",
    },
    {
        // "article_id": 7,
        "user_id": 20,
        "category_id": 2,
        "tag_ids": [1,3],
        "link_url": "",
        "cover_image": "",
        "title": "让你的小程序用上原汁原味的 Tailwind/Windi CSS (JIT 兼容版) （测试标题 后端）",
        "brief_content": "这里是一个摘要（测试摘要 ）",
        "content": content,
        "visible_level": "0",
        "view_count": 0,
        "status": "1",
    },
    /** 前端 -----------------------------------------------------------------------------*/
    {
        // "article_id": 7,
        "user_id": 20,
        "category_id": 3,
        "tag_ids": [1, 2, 3],
        "link_url": "",
        "cover_image": "",
        "title": "Vue前端实现HTML转PDF并导出 （测试标题 算法）",
        "brief_content": "这里是一个摘要（测试摘要 ）",
        "content": content,
        "visible_level": "0",
        "view_count": 0,
        "status": "1",
    },
    /** 前端 -----------------------------------------------------------------------------*/
    {
        // "article_id": 7,
        "user_id": 20,
        "category_id": 4,
        "tag_ids": [3],
        "link_url": "",
        "cover_image": "",
        "title": "Vue前端实现HTML转PDF并导出 （测试标题 Android））",
        "brief_content": "这里是一个摘要（测试摘要 ）",
        "content": content,
        "visible_level": "0",
        "view_count": 0,
        "status": "1",
    },
    /** 前端 -----------------------------------------------------------------------------*/
    {
        // "article_id": 7,
        "user_id": 20,
        "category_id": 5,
        "tag_ids": [1, 2],
        "link_url": "",
        "cover_image": "",
        "title": "Vue前端实现HTML转PDF并导出 （测试标题 IOS）",
        "brief_content": "这里是一个摘要（测试摘要 ）",
        "content": content,
        "visible_level": "0",
        "view_count": 0,
        "status": "1",
    },
    /** 前端 -----------------------------------------------------------------------------*/
    {
        // "article_id": 7,
        "user_id": 20,
        "category_id": 6,
        "tag_ids": [1, 3],
        "link_url": "",
        "cover_image": "",
        "title": "Vue前端实现HTML转PDF并导出 （测试标题 随笔）",
        "brief_content": "这里是一个摘要（测试摘要 ）",
        "content": content,
        "visible_level": "0",
        "view_count": 0,
        "status": "1",
    },

]